/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package src;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis m
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programable = new javax.swing.ButtonGroup();
        grados = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        basico1 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        division = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        por = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        negativo = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        euler = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        retroceso = new javax.swing.JButton();
        sobre = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        div = new javax.swing.JButton();
        equ = new javax.swing.JButton();
        rad = new javax.swing.JRadioButton();
        grado = new javax.swing.JRadioButton();
        trig = new javax.swing.JComboBox<>();
        display2 = new javax.swing.JTextField();
        prog = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        types = new javax.swing.JMenu();
        cientifico = new javax.swing.JMenuItem();
        programadora = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(1, 1, 1));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(630, 710));

        jPanel1.setBackground(new java.awt.Color(20, 23, 25));

        display.setEditable(false);
        display.setBackground(new java.awt.Color(1, 1, 1));
        display.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setText("0");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        basico1.setBackground(new java.awt.Color(20, 23, 25));
        basico1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn7.setBackground(new java.awt.Color(1, 1, 1));
        btn7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setToolTipText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(1, 1, 1));
        btn8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setToolTipText("7");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(1, 1, 1));
        btn9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setToolTipText("7");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(1, 1, 1));
        division.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        division.setForeground(new java.awt.Color(255, 255, 255));
        division.setText("÷");
        division.setToolTipText("7");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(1, 1, 1));
        btn4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setToolTipText("7");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(1, 1, 1));
        btn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setToolTipText("7");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(1, 1, 1));
        btn6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setToolTipText("7");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        por.setBackground(new java.awt.Color(1, 1, 1));
        por.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        por.setForeground(new java.awt.Color(255, 255, 255));
        por.setText("*");
        por.setToolTipText("7");
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(1, 1, 1));
        btn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setToolTipText("7");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(1, 1, 1));
        btn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setToolTipText("7");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(1, 1, 1));
        btn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setToolTipText("7");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        menos.setBackground(new java.awt.Color(1, 1, 1));
        menos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 255, 255));
        menos.setText("-");
        menos.setToolTipText("7");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        negativo.setBackground(new java.awt.Color(1, 1, 1));
        negativo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        negativo.setForeground(new java.awt.Color(255, 255, 255));
        negativo.setText("+/-");
        negativo.setToolTipText("7");
        negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativoActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(1, 1, 1));
        btn0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setToolTipText("7");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(1, 1, 1));
        punto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        punto.setForeground(new java.awt.Color(255, 255, 255));
        punto.setText(".");
        punto.setToolTipText("7");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        mas.setBackground(new java.awt.Color(1, 1, 1));
        mas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("+");
        mas.setToolTipText("7");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        pi.setBackground(new java.awt.Color(1, 1, 1));
        pi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pi.setForeground(new java.awt.Color(255, 255, 255));
        pi.setText("π");
        pi.setToolTipText("7");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        euler.setBackground(new java.awt.Color(1, 1, 1));
        euler.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        euler.setForeground(new java.awt.Color(255, 255, 255));
        euler.setText("e");
        euler.setToolTipText("7");
        euler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulerActionPerformed(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(1, 1, 1));
        borrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("C");
        borrar.setToolTipText("7");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        retroceso.setBackground(new java.awt.Color(49, 88, 119));
        retroceso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        retroceso.setForeground(new java.awt.Color(255, 255, 255));
        retroceso.setText("←");
        retroceso.setToolTipText("7");
        retroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrocesoActionPerformed(evt);
            }
        });

        sobre.setBackground(new java.awt.Color(1, 1, 1));
        sobre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sobre.setForeground(new java.awt.Color(255, 255, 255));
        sobre.setText("1/X");
        sobre.setToolTipText("7");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });

        factorial.setBackground(new java.awt.Color(1, 1, 1));
        factorial.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        factorial.setForeground(new java.awt.Color(255, 255, 255));
        factorial.setText("n!");
        factorial.setToolTipText("7");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });

        raiz.setBackground(new java.awt.Color(1, 1, 1));
        raiz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        raiz.setForeground(new java.awt.Color(255, 255, 255));
        raiz.setText("√");
        raiz.setToolTipText("7");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });

        potencia.setBackground(new java.awt.Color(1, 1, 1));
        potencia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        potencia.setForeground(new java.awt.Color(255, 255, 255));
        potencia.setText("X^y");
        potencia.setToolTipText("7");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        mod.setBackground(new java.awt.Color(1, 1, 1));
        mod.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mod.setForeground(new java.awt.Color(255, 255, 255));
        mod.setText("Mod");
        mod.setToolTipText("7");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(1, 1, 1));
        div.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("Div");
        div.setToolTipText("7");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        equ.setBackground(new java.awt.Color(49, 88, 119));
        equ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        equ.setForeground(new java.awt.Color(255, 255, 255));
        equ.setText("=");
        equ.setToolTipText("7");
        equ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equActionPerformed(evt);
            }
        });

        grados.add(rad);
        rad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rad.setForeground(new java.awt.Color(255, 255, 255));
        rad.setText("RADIANES");

        grados.add(grado);
        grado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        grado.setForeground(new java.awt.Color(255, 255, 255));
        grado.setSelected(true);
        grado.setText("GRADOS");

        trig.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        trig.setForeground(new java.awt.Color(255, 255, 255));
        trig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trigonometrica", "sin", "cos", "tan" }));
        trig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basico1Layout = new javax.swing.GroupLayout(basico1);
        basico1.setLayout(basico1Layout);
        basico1Layout.setHorizontalGroup(
            basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basico1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(mod)
                        .addGap(18, 18, 18)
                        .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(euler, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(retroceso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basico1Layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(equ, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad)
                .addGap(43, 43, 43))
        );
        basico1Layout.setVerticalGroup(
            basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basico1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rad)
                        .addComponent(grado))
                    .addComponent(trig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euler, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retroceso, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        display2.setEditable(false);
        display2.setBackground(new java.awt.Color(1, 1, 1));
        display2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        display2.setForeground(new java.awt.Color(255, 255, 255));
        display2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display2ActionPerformed(evt);
            }
        });

        prog.setBackground(new java.awt.Color(20, 23, 25));
        prog.setVisible(false);

        programable.add(jToggleButton1);
        jToggleButton1.setText("jToggleButton1");

        programable.add(jToggleButton5);
        jToggleButton5.setText("jToggleButton1");

        programable.add(jToggleButton6);
        jToggleButton6.setText("jToggleButton1");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        programable.add(jToggleButton7);
        jToggleButton7.setSelected(true);
        jToggleButton7.setText("jToggleButton1");

        javax.swing.GroupLayout progLayout = new javax.swing.GroupLayout(prog);
        prog.setLayout(progLayout);
        progLayout.setHorizontalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(progLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        progLayout.setVerticalGroup(
            progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(progLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(progLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(basico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(display))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        types.setMnemonic('t');
        types.setText("Type");
        types.setFocusable(false);
        types.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        cientifico.setMnemonic('c');
        cientifico.setText("Científico");
        cientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cientificoActionPerformed(evt);
            }
        });
        types.add(cientifico);

        programadora.setMnemonic('p');
        programadora.setText("Programadora");
        programadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programadoraActionPerformed(evt);
            }
        });
        types.add(programadora);

        jMenuBar1.add(types);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("res/calc2.png"));


        return retValue;
    }
    String d2,d1;
    double res = 0;
    boolean primera = true, first = true, finish = false,operador = true;
    double pii = Math.PI, eu = Math.E;
    
    private double eval(String signo, double n1, double n2){
        double num = 0;
        switch (signo){
            case "+":
                num =  n1+n2;
                break;
            case "-":
                num = n1-n2;
                break;
            case "*":
                num = n1 * n2;
                break;
            case "÷":
                num = n1/n2;
                break;
            case "%":
                num = n1 % n2;
                break;
            case "v":
                int num1 = (int) ((int) n1/n2);
                num = num1;
                break;
            case "^":
                if (n2 == 0){
                    num = 1;
                } else {
                    if(n2 < 0){
                        double pot =n1;
                        for (int i =1; i< n2*-1;i++){
                            pot = pot * n1;
                        }
                        num = 1/pot;
                    } else {
                        double pot = n1;
                        for (int i = 1;i < n2; i++){
                            pot = pot * n1;
                        }
                        num = pot;
                    }
                    
                }
                break;
        }
        
        return num;
                
    }
    
    private void cientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cientificoActionPerformed
        // TODO add your handling code here:
        System.out.println("Hola soy Cientifico");
        prog.setVisible(false);
    }//GEN-LAST:event_cientificoActionPerformed

    private void programadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programadoraActionPerformed
        // TODO add your handling code here:
        System.out.println("Hola soy programable");
        prog.setVisible(true);
        jPanel1.setSize(1000, 500);
        
    }//GEN-LAST:event_programadoraActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display2ActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"div");
//            d1 = "0";
            String ress = String.valueOf(res);
            display.setText(ress);
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("("+d2+d1+")"+"div");
            String ress = String.valueOf(res);
            display.setText(ress);
        }
    }//GEN-LAST:event_divActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"%");
            String ress = String.valueOf(res);
            display.setText(ress);
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("("+d2+d1+")"+"%");
            String ress = String.valueOf(res);
            display.setText(ress);
        }
    }//GEN-LAST:event_modActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"^");
//            d1 = "0";
            display.setText(String.valueOf(res));
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("("+d2+d1+")"+"^");
            display.setText(String.valueOf(res));
        }
    }//GEN-LAST:event_potenciaActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        // TODO add your handling code here:
        operador = true;
        double d11 = 0;
        String pantalla ="";
        if(primera){
            d1 = display.getText();
            d11 = Double.parseDouble(d1);
            primera = false;
            pantalla=d1;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            d11 = res;
            pantalla = d2;
            
        }
        
        display2.setText("√("+pantalla+d1+")=");
        d11 = Math.sqrt(d11);
        display.setText(String.valueOf(d11));
        primera = true;
        res = 0;
    }//GEN-LAST:event_raizActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
        // TODO add your handling code here:
        operador = true;
        double fac = 1;
        if(primera){
            d1 = display.getText();
            
            for(int i = 1; i<= Double.parseDouble(d1);i++){
                fac = fac * i;
            }
            display2.setText(d1+"!=");
            display.setText(String.valueOf(fac));
            primera = false;
        } else {
             d2 = display2.getText();
            d1 = display.getText();
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            for(int i = 1; i<= res;i++){
                fac = fac * i;
            }
            display2.setText("("+d2+d1+")!=");
            display.setText(String.valueOf(fac));
        }
        primera = true;
        res = 0;
    }//GEN-LAST:event_factorialActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        // TODO add your handling code here:
        operador = true;
        if(primera){
            d1 = display.getText();
            res = 1 / Double.parseDouble(d1);
            display2.setText("1/"+d1+"=");
            display.setText(String.valueOf(res));
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("1/("+d2+d1+")=");
            double fac = 1/res;
            display.setText(String.valueOf(fac));
        }
        primera = true;
        res = 0;
        
    }//GEN-LAST:event_sobreActionPerformed

    private void retrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrocesoActionPerformed
        // TODO add your handling code here:
        d1 = display.getText();
        System.out.println(d1.length());
        if(d1.length() == 1){
            if(!d1.equals("0")){
                display.setText("0");
                primera = true; finish = false;operador = true;
            }
        } else {
            display.setText(d1.substring(0, d1.length()-1)); 

        }
        
        
    }//GEN-LAST:event_retrocesoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        primera = true; first = true; finish = false;operador = true;
        display.setText("0");
        display2.setText("");
        res = 0;
    }//GEN-LAST:event_borrarActionPerformed

    private void eulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulerActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+String.valueOf(eu));
    }//GEN-LAST:event_eulerActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+String.valueOf(pii));
       
    }//GEN-LAST:event_piActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"+");
            d1 = "0";
            String ress = String.valueOf(res);
            display.setText(ress);
            primera = false;
            
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText(d2+d1+"+");
            String ress = String.valueOf(res);
            display.setText(ress);
        }
        
        
    }//GEN-LAST:event_masActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
        if(first){
            d1 = display.getText();
            display.setText(d1+".");
            first = false;
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity")){
            display.setText("");
            d1 = display.getText();
            finish = false;
        }
        display.setText(d1+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativoActionPerformed
        // TODO add your handling code here:
        d1 = display.getText();
        Object d11 = 0 ;
        try {
            d11 = (int)  Integer.parseInt(d1) *-1;
        } catch (Exception e) {
            d11 = Double.parseDouble(d1) *-1;
        }
        display.setText(String.valueOf(d11));
        
    }//GEN-LAST:event_negativoActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"-");
//            d1 = "0";
            String ress = String.valueOf(res);
            display.setText(ress);;
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText(d2+d1+"-");
            String ress = String.valueOf(res);
            display.setText(ress);;
        }
    }//GEN-LAST:event_menosActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"2");
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
           }  
        }
        
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador  = false;
        }
        display.setText(d1+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"*");
            String ress = String.valueOf(res);
            display.setText(ress);
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("("+d2+d1+")"+"*");
            String ress = String.valueOf(res);
            display.setText(ress);;
        }
    }//GEN-LAST:event_porActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=") ){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
                   
        }
        display.setText(d1+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
        operador = true;
        if (primera){
            d1 = display.getText();
            res = res + Double.parseDouble(d1);
            display2.setText(d1+"÷");      
            String ress = String.valueOf(res);
            display.setText(ress);
            primera = false;
        } else {
            d2 = display2.getText();
            d1 = display.getText();
            System.out.println(d2.substring(d2.length()-1, d2.length()));
            String opt = d2.substring(d2.length()-1, d2.length());
            res = eval(opt, res, Double.parseDouble(d1));
            display2.setText("("+d2+d1+")"+"÷");
            String ress = String.valueOf(res);
            display.setText(ress);
        }
    }//GEN-LAST:event_divisionActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        if(!d2.isEmpty()){
          if(d2.substring(d2.length()-1,d2.length()).equals("=")){
            display2.setText("");
            finish = true;
        }  
        }
        
        
        d1 = display.getText();
        if(d1.equals("0") || finish || d1.equals("Infinity") || operador){
            display.setText("");
            d1 = display.getText();
            finish = false;
            operador = false;
        }
        display.setText(d1+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void equActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equActionPerformed
        // TODO add your handling code here:
        d2 = display2.getText();
        d1 = display.getText();
        String opt = d2.substring(d2.length()-1, d2.length());
        res = eval(opt, res, Double.parseDouble(d1));
        display2.setText(d2+d1+"=");
        String ress = String.valueOf(res);
        display.setText(ress);
        res = 0;
        primera = true;
    }//GEN-LAST:event_equActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed
    private double factorial(double x){
        double fac = 1;
        for (int i = 1; i<=x;i++){
            fac = fac * i;
        }
        return fac;
    }
    private double pot(double n1, double n2){
        double pot = n1;
        if (n2== 0){
            pot = 1;
        }else{
            for (int i = 1; i<n2;i++){
            pot = pot * n1;
        }
        }
        
        return pot;
    }
    private double sin(double x){
        double sum = 0,pot1,pot2,fac, valor;
        for (int i = 0; i<=70;i++){
            valor = 2*i+1;
            pot1 = pot(-1,i);
            pot2 = pot(x,valor);
            fac = factorial(valor);
            sum = sum + (pot1*pot2)/(fac);
        }
        return sum;
    }
    private double cos(double x){
        double sum = 0,pot1,pot2,fac, valor;;
        for (int i = 0; i<=70;i++){
            valor = 2*i;
            pot1 = pot(-1,i);
            pot2= pot(x,valor);
            fac = factorial(valor);
            sum = sum + (pot1*pot2)/(fac);
        }
        return sum;
    }
    private double tan(double x){
        return sin(x)/cos(x);
    }
    private void trigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trigActionPerformed
        // TODO add your handling code here:
        String Opt = trig.getSelectedItem().toString();
        d1 = display.getText();
        double d11 = Double.parseDouble(d1);
        double rad = 0;
        if(grado.isSelected()){
            while(d11>360){
                d11 = d11 - 360;
            }
            rad = d11*pii/180;
            
        } else {
            while (d11 > 2*pii){
                d11 = d11 - 2*pii;
            }
            rad = d11;
        }
        switch (Opt){
            case "sin":
                d1 = display.getText();
                display2.setText("sin("+d1+")=");
                display.setText(String.valueOf(sin(rad)));                            
                break;
            case "cos":
                d1 = display.getText();
                display2.setText("cos("+d1+")=");
                display.setText(String.valueOf(cos(rad))); 
                break;
            case "tan":
                d1 = display.getText();
                display2.setText("tan("+d1+")=");
                display.setText(String.valueOf(tan(rad))); 
                break;
        }
        
    }//GEN-LAST:event_trigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basico1;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JMenuItem cientifico;
    private javax.swing.JTextField display;
    private javax.swing.JTextField display2;
    private javax.swing.JButton div;
    private javax.swing.JButton division;
    private javax.swing.JButton equ;
    private javax.swing.JButton euler;
    private javax.swing.JButton factorial;
    private javax.swing.JRadioButton grado;
    private javax.swing.ButtonGroup grados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton mod;
    private javax.swing.JButton negativo;
    private javax.swing.JButton pi;
    private javax.swing.JButton por;
    private javax.swing.JButton potencia;
    private javax.swing.JPanel prog;
    private javax.swing.ButtonGroup programable;
    private javax.swing.JMenuItem programadora;
    private javax.swing.JButton punto;
    private javax.swing.JRadioButton rad;
    private javax.swing.JButton raiz;
    private javax.swing.JButton retroceso;
    private javax.swing.JButton sobre;
    private javax.swing.JComboBox<String> trig;
    private javax.swing.JMenu types;
    // End of variables declaration//GEN-END:variables
}
